fix: check for docstatus if doc is submittable
agritheory/approvals pull request #63
Opened 2024-07-23 10:21 UTC by MyuddinKhatri

closes #45 

check for docstatus if doc is submittable instead of string "Approved"

2024-07-23 10:31 UTC, MyuddinKhatri commented
@agritheory json_diff is complaining about field_name does not exist in property setter, pre-commit removed it its value was null, should we add a check to ignore `field_name` while iterating through property setter to leave it as it is even though the value is null?

2024-07-23 13:06 UTC, agritheory commented on approvals/approvals/custom/todo.json
> +    {
Let's not include this opinion in general purpose / non-customer apps

2024-07-24 11:35 UTC, agritheory requested changes

2024-07-24 11:35 UTC, agritheory commented on approvals/approvals/api.py
> +	if doc.meta.is_submittable:
This can be combined into a single statement

2024-08-05 18:52 UTC, agritheory approved these changes

2024-10-17 14:17 UTC, merged